#!/usr/bin/env bash
# half-loop.sh — Bridge AI execution loop for AI CLI agents inside Docker sandbox.
#
# Runs iteratively until the AI outputs the completion sentinel or max iterations
# is reached. Compatible with Claude CLI and Gemini CLI via wrapper pattern.
#
# Usage:
#   half-loop.sh --prompt-file <path> [--max-iterations N] [--stop-file <path>]
#
# Environment:
#   BRIDGE_AI_CMD          AI CLI command to use (default: claude)
#   BRIDGE_MAX_ITERATIONS  Max loop iterations (default: 12)
#   BRIDGE_LOGS_DIR        Directory for iteration logs (default: .bridge/logs)
#   BRIDGE_PROGRESS_FILE   Cumulative progress file (default: .bridge/progress.txt)
#   BRIDGE_COMPLETION_PROMISE  Sentinel string (default: <promise>COMPLETE</promise>)
set -euo pipefail

AI_CMD="${BRIDGE_AI_CMD:-claude}"
MAX_ITERATIONS="${BRIDGE_MAX_ITERATIONS:-12}"
COMPLETION_PROMISE="${BRIDGE_COMPLETION_PROMISE:-<promise>COMPLETE</promise>}"
PROGRESS_FILE="${BRIDGE_PROGRESS_FILE:-.bridge/progress.txt}"
LOGS_DIR="${BRIDGE_LOGS_DIR:-.bridge/logs}"
PROMPT_FILE=""
STOP_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prompt-file)
      PROMPT_FILE="$2"
      shift 2
      ;;
    --max-iterations)
      MAX_ITERATIONS="$2"
      shift 2
      ;;
    --stop-file)
      STOP_FILE="$2"
      shift 2
      ;;
    --completion-promise)
      COMPLETION_PROMISE="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "${PROMPT_FILE}" ]]; then
  echo "Missing required argument --prompt-file" >&2
  exit 1
fi

if [[ ! -f "${PROMPT_FILE}" ]]; then
  echo "Prompt file not found: ${PROMPT_FILE}" >&2
  exit 1
fi

mkdir -p "$(dirname "${PROGRESS_FILE}")"
mkdir -p "${LOGS_DIR}"
touch "${PROGRESS_FILE}"

# Preserve HOME and Claude config vars across container user switches
if [[ -n "${CLAUDE_CONFIG_DIR:-}" ]]; then
  export CLAUDE_CONFIG_DIR
fi
if [[ -n "${CLAUDE_CONFIG_FILE:-}" ]]; then
  export CLAUDE_CONFIG_FILE
fi
if [[ -n "${HOME:-}" ]]; then
  export HOME
fi

# Ensure git identity is set (required for commits inside container)
if [[ -z "$(git config user.email 2>/dev/null || true)" ]]; then
  git config --global user.email "${GIT_AUTHOR_EMAIL:-gsd@bridge-ai.local}"
  git config --global user.name "${GIT_AUTHOR_NAME:-GSD (bridge-ai)}"
  git config --global init.defaultBranch main
fi

# Initialize git repo if workspace is not already one
if [[ ! -d ".git" ]]; then
  echo "Initializing git in workspace..."
  git init
  git add -A
  git commit -m "chore: initial workspace commit (auto-generated by bridge-ai)" --allow-empty
fi

# Write static .claude/settings.json with scoped permissions.
# NO wildcard allow — explicit tool list only.
SETTINGS_DIR=".claude"
mkdir -p "${SETTINGS_DIR}"
cat > "${SETTINGS_DIR}/settings.json" << 'SETTINGS_EOF'
{
  "permissions": {
    "allow": [
      "Write(**)",
      "Edit(**)",
      "Read(**)",
      "Bash(npm *)",
      "Bash(node *)",
      "Bash(npx *)",
      "Bash(bun *)",
      "Bash(bunx *)",
      "Bash(mkdir *)",
      "Bash(cat *)",
      "Bash(echo *)",
      "Bash(tee *)",
      "Bash(ls *)",
      "Bash(find *)",
      "Bash(grep *)",
      "Bash(rg *)",
      "Bash(git *)",
      "Bash(cp *)",
      "Bash(mv *)",
      "Bash(rm *)",
      "Bash(touch *)",
      "Bash(chmod *)",
      "Bash(head *)",
      "Bash(tail *)",
      "Bash(wc *)",
      "Bash(sed *)",
      "Bash(awk *)"
    ],
    "deny": []
  }
}
SETTINGS_EOF

BASE_PROMPT="$(cat "${PROMPT_FILE}")"

echo "bridge-ai half-loop starting: max_iterations=${MAX_ITERATIONS}"
echo "BRIDGE_STATUS state=started max=${MAX_ITERATIONS}"

for ((i=1; i<=MAX_ITERATIONS; i++)); do
  if [[ -n "${STOP_FILE}" && -f "${STOP_FILE}" ]]; then
    echo "BRIDGE_STATUS state=stopped iteration=${i}"
    echo "Stop signal detected at iteration ${i}" >&2
    exit 130
  fi

  ITER_LOG="${LOGS_DIR}/iteration-${i}.md"
  echo "Running iteration ${i}/${MAX_ITERATIONS}"
  echo "BRIDGE_STATUS state=running iteration=${i} max=${MAX_ITERATIONS}"

  CONTEXT=""
  if [[ -s "${PROGRESS_FILE}" ]]; then
    CONTEXT="$(tail -n 120 "${PROGRESS_FILE}")"
  fi

  ITER_PROMPT=$(cat <<EOF
${BASE_PROMPT}

Loop iteration: ${i}/${MAX_ITERATIONS}
Use git history and the codebase as memory.
Append concise progress notes to .bridge/progress.txt.
If all requested work is complete, output exactly: ${COMPLETION_PROMISE}

Recent progress context:
${CONTEXT}
EOF
)

  set +e
  OUTPUT="$(${AI_CMD} -p "${ITER_PROMPT}" 2>&1)"
  EXIT_CODE=$?
  set -e

  {
    echo "# Iteration ${i}"
    echo
    echo '```text'
    echo "${OUTPUT}"
    echo '```'
  } > "${ITER_LOG}"

  {
    echo "## Iteration ${i} ($(date -Iseconds))"
    echo "${OUTPUT}"
    echo
  } >> "${PROGRESS_FILE}"

  if [[ ${EXIT_CODE} -ne 0 ]]; then
    echo "BRIDGE_STATUS state=iteration_failed iteration=${i} exit_code=${EXIT_CODE}"
    echo "Iteration ${i} failed (exit ${EXIT_CODE})" >&2

    # Authentication/config errors are fatal — exit with code 3
    if echo "${OUTPUT}" | grep -qiE \
      "configuration file not found|\.claude\.json|auth.*required|not logged in|unauthenticated|oauth token has expired|authentication_error|failed to authenticate|api error: 401"; then
      echo "BRIDGE_STATUS state=fatal_auth_error iteration=${i}"
      echo "Fatal: AI CLI auth/config error. Stopping loop." >&2
      exit 3
    fi

    # Permission errors — exit with code 1 instead of expanding permissions
    if echo "${OUTPUT}" | grep -qiE "permission|blocked|requires.*approval"; then
      echo "BRIDGE_STATUS state=fatal_permission_error iteration=${i}"
      echo "Fatal: Permission error. Settings.json may be misconfigured." >&2
      exit 1
    fi

    continue
  fi

  if grep -Fq "${COMPLETION_PROMISE}" "${ITER_LOG}"; then
    echo "Completed at iteration ${i}"
    echo "BRIDGE_STATUS state=completed iteration=${i}"
    exit 0
  fi
done

echo "Reached max iterations (${MAX_ITERATIONS}) without completion sentinel" >&2
echo "BRIDGE_STATUS state=max_iterations_reached max=${MAX_ITERATIONS}"
exit 2
